### ISSUE TITLE
Prefixed boolean variables

### ISSUE THREAD

**Issue by cosminnicula** [telerik/kendo-react-inputs#14]
It is a commonly used practice to prefix the boolean variables with "is" / "has" / "can" etc.
For example `/src/slider/Slider.jsx` has a `disabled` property which could be renamed to `isDisabled`. Same for `buttons`, `vertical` etc.

**Comment by tsvetomir** [comment]
I agree, especially for `buttons`. A more clear name would be `showButtons`.
The rest are not that confusing to me.

**Comment by cosminnicula** [comment]
It might worth the effort to have all the booleans named in the same way. Clear APIs are also about consistency and semantics, but I'll let you decide on this :)

**Comment by KirilNN** [comment]
I agree that the `buttons` option should be renamed to `showButtons` and this should be fixed with the following pull request: https://github.com/telerik/kendo-react-inputs/pull/17

as for prefixing the boolean variables - we currently agree on not prefixing them.

Thanks for the suggestion @cosminnicula.
